development:
  adapter: postgresql
  encoding: unicode
  database: thanksgiving_development
  pool: 5
  username: rails
  password: railspw

test:
  adapter: postgresql
  encoding: unicode
  database: thanksgiving_test
  pool: 5
  username: rails
  password: railspw
