default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['RAILS_POSTGRES_USER'] %>
  password:

development:
  <<: *default
  database: thanksgiving_development

test:
  <<: *default
  database: thanksgiving_test
